<a href="https://colab.research.google.com/github/jovisonmedeiros/Desafio-IA/blob/main/Iris_DeepLearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Importa a biblioteca TensorFlow, que é uma biblioteca de aprendizado de máquina.
import tensorflow as tf

# Importa a função `load_iris` do scikit-learn, que carrega o dataset Iris.
from sklearn.datasets import load_iris

# Carrega o dataset Iris, que é um conjunto de dados muito utilizado em aprendizado de máquina.
data = load_iris()

# Importa a função `train_test_split` do scikit-learn, que é usada para dividir o dataset em conjuntos de treinamento e teste.
from sklearn.model_selection import train_test_split

# Divide o dataset em conjuntos de treinamento e teste.
# `test_size=0.33` indica que 33% dos dados serão usados para teste e 67% para treinamento.
# `random_state=42` garante que a divisão dos dados seja a mesma em cada execução.
# x são as entradas e y as saídas
x_train, x_test, y_train, y_test = train_test_split(data.data, data.target, test_size=0.33, random_state=42)

# Cria um modelo sequencial do TensorFlow Keras.
# O modelo é uma sequência de camadas aplicadas umas após as outras.
model = tf.keras.models.Sequential([
  # Adiciona uma camada de flattening, que transforma uma matriz 2D (ou maior) em um vetor 1D.
  tf.keras.layers.Flatten(),

  # Adiciona uma camada densa com 512 neurônios e uma função de ativação ReLU.
  # A ReLU (Rectified Linear Unit) é uma função não-linear que ajuda o modelo a aprender relações complexas.
  tf.keras.layers.Dense(512, activation=tf.nn.relu),

  # Adiciona uma camada de dropout que desativa 20% dos neurônios aleatoriamente durante o treinamento.
  # Isso ajuda a evitar overfitting (ajuste excessivo) do modelo.
  #tf.keras.layers.Dropout(0.2),

  # Adiciona uma camada densa com 10 neurônios e uma função de ativação softmax.
  # A softmax é usada para problemas de classificação multi-classe e produz probabilidades que somam 1.
  tf.keras.layers.Dense(10, activation=tf.nn.softmax)
])

# Compila o modelo especificando o otimizador, a função de perda e as métricas a serem avaliadas.
# `optimizer='adam'` é um algoritmo de otimização popular que ajusta os pesos do modelo.
# `loss='sparse_categorical_crossentropy'` é a função de perda para problemas de classificação multi-classe.
# `metrics=['accuracy']` indica que a precisão deve ser calculada durante o treinamento e avaliação.
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# Treina o modelo com os dados de treinamento.
# `epochs=50` indica que o modelo passará pelos dados de treinamento 50 vezes.
model.fit(x_train, y_train, epochs=50)

# Avalia o modelo com os dados de teste para verificar seu desempenho.
model.evaluate(x_test, y_test)


Epoch 1/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 5s 57ms/step - accuracy: 0.0000e+00 - loss: 2.5208
Epoch 2/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.3618 - loss: 1.7260
Epoch 3/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.6454 - loss: 1.2791 
Epoch 4/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.6612 - loss: 1.0343 
Epoch 5/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.6527 - loss: 0.9109 
Epoch 6/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6767 - loss: 0.8326
Epoch 7/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.9439 - loss: 0.7622 
Epoch 8/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8971 - loss: 0.7138
Epoch 9/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.8765 - loss: 0.6762
Epoch 10/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7576 - loss: 0.6297 
Epoch 11/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.6683 - loss: 0.6079 
Epoch 12/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.6079 - loss

[0.19407689571380615, 1.0]

In [ ]:
#Conteúdo completo
data.data.size

600

In [ ]:
import numpy as np
from sklearn.metrics import confusion_matrix

# Faz previsões no conjunto de teste.
previsoes_prob = model.predict(x_test)

# Converte as probabilidades previstas em rótulos de classe.
previsoes = np.argmax(previsoes_prob, axis=1)

# Calcula a matriz de confusão.
matrix = confusion_matrix(y_test, previsoes)

print(matrix)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
[[19  0  0]
 [ 0 15  0]
 [ 0  1 15]]
